"""create url clicks table

Revision ID: 9f0c6a80144c
Revises: 7cbb4fcad68f
Create Date: 2026-08-25 23:16:16.510931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0c6a80144c'
down_revision: Union[str, Sequence[str], None] = '7cbb4fcad68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_clicks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_clicks_clicked_at'), 'url_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_url_clicks_url_id'), 'url_clicks', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_clicks_url_id'), table_name='url_clicks')
    op.drop_index(op.f('ix_url_clicks_clicked_at'), table_name='url_clicks')
    op.drop_table('url_clicks')
    # ### end Alembic commands ###
